image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Flutter
    init: |
      sudo apt-get update
      sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
      git clone https://github.com/flutter/flutter.git -b stable
      echo 'export PATH="$PATH:/workspace/flutter/bin"' >> ~/.bashrc
      source ~/.bashrc
      flutter --version
      flutter doctor
    command: |
      flutter doctor
