tasks:
  - name: Install Flutter
    init: |
      sudo apt-get update
      sudo apt-get install -y git curl unzip xz-utils zip libglu1-mesa
      git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
      echo 'export PATH="$PATH:$HOME/flutter/bin"' >> ~/.bashrc
      source ~/.bashrc
      flutter --version
    command: |
      flutter doctor

vscode:
  extensions:
    - Dart-Code.flutter
